### ISSUE TITLE
Where are the benchmarks against other Rust implementations?

### ISSUE THREAD

**Issue by magnus-ISU** [aldanor/qoi-rust#1]
Title

**Comment by aldanor** [comment]
- Comparison with [`rapid_qoi`](https://github.com/zakarumych/rapid-qoi) - see [here](https://github.com/phoboslab/qoi/pull/164#issue-1094876247)
- These crates are no longer compliant with the latest spec, so can't compare right now:
  - [`qoi_rs`](https://github.com/ChevyRay/qoi_rs)
  - [`img-qoi`](https://github.com/taotao54321/img-qoi)
  - [`qoi <0.4.0`](https://github.com/steven-joruk/qoi) (same name as this crate)
- Before the final version of the spec has been posted, I've shared some preliminary benchmarks against a few crates [here](https://github.com/phoboslab/qoi/issues/46#issuecomment-981291420) and at the time of writing it was also the fastest one. This, however, was a long time ago and most of the code was essentially rewritten after the final spec was released.

**Comment by aldanor** [comment]
Closing as the answer has been provided.
